# Generated by Django 4.2 on 2025-01-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account_name',
            field=models.CharField(default='', max_length=50, verbose_name='ユーザー名'),
        ),
    ]
