# Generated by Django 4.2 on 2025-01-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account_name',
            field=models.CharField(default='', max_length=50, verbose_name='ユーザーネーム'),
        ),
    ]
