# Generated by Django 4.2 on 2024-11-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=500, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='users',
            name='start_password',
            field=models.CharField(max_length=500, verbose_name='初期パスワード'),
        ),
    ]
