# Generated by Django 4.2 on 2024-11-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_company_id_users_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='company_name',
            new_name='company',
        ),
    ]
