# Generated by Django 4.2 on 2024-11-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='account_name',
        ),
        migrations.AddField(
            model_name='notification',
            name='account_id',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='ユーザーID'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company_id',
            field=models.CharField(max_length=50, null=True, verbose_name='企業ID'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
