# Generated by Django 4.2 on 2025-01-24 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harassment_report',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='企業id'),
        ),
    ]
