# Generated by Django 4.2 on 2024-11-17 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_users_account_id_users_groups_users_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='account_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='管理者ID'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='is_superuser'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='企業名'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='企業ID'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='keyword',
            field=models.CharField(max_length=100, verbose_name='単語'),
        ),
        migrations.AlterField(
            model_name='error_report',
            name='error_detail',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='error_report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='error_report',
            name='report_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='報告日時'),
        ),
        migrations.AlterField(
            model_name='harassment_report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='harassment_report',
            name='report_detail',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='harassment_report',
            name='report_image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='harassment_report',
            name='report_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='報告日時'),
        ),
        migrations.AlterField(
            model_name='text',
            name='detected_words',
            field=models.CharField(max_length=100, null=True, verbose_name='検出単語'),
        ),
        migrations.AlterField(
            model_name='text',
            name='harassment_flag',
            field=models.BooleanField(default=False, verbose_name='ハラスメントフラグ'),
        ),
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='text',
            name='input_text',
            field=models.TextField(verbose_name='入力文章'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_flag',
            field=models.BooleanField(default=False, verbose_name='テキストフラグ'),
        ),
        migrations.AlterField(
            model_name='users',
            name='account_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=50, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='users',
            name='start_password',
            field=models.CharField(max_length=50, verbose_name='初期パスワード'),
        ),
        migrations.AlterField(
            model_name='users',
            name='superuser_flag',
            field=models.BooleanField(default=False, verbose_name='スーパーユーザーフラグ'),
        ),
    ]
