# Generated by Django 4.2 on 2024-11-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_notification_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='account_id',
            field=models.CharField(max_length=50, null=True, verbose_name='ユーザーID'),
        ),
    ]
