# Generated by Django 4.2 on 2025-01-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_harassment_report_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harassment_report',
            old_name='company_id',
            new_name='company',
        ),
    ]
