# Generated by Django 4.2 on 2024-11-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_notification_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='superuser_id',
            field=models.CharField(max_length=50, null=True, verbose_name='スーパーユーザーID'),
        ),
    ]
