# Generated by Django 4.2 on 2024-11-17 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_admin_account_id_alter_admin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='企業名'),
        ),
    ]
