# Generated by Django 4.2 on 2025-01-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_company_id_harassment_report_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='error_report',
            name='inquiry_type',
            field=models.CharField(choices=[('type1', 'サービスについて'), ('type2', 'アカウント・ログインについて'), ('type3', '不具合について'), ('type4', '改善要望'), ('type5', 'その他')], default='type1', max_length=50, verbose_name='お問い合わせ種類'),
        ),
    ]
