# Generated by Django 4.2 on 2024-12-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_harassment_report_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='harassment_report',
            name='report_title',
            field=models.CharField(default='', max_length=50, verbose_name='タイトル'),
        ),
    ]
