# Generated by Django 4.2 on 2024-11-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_notification_superuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='account_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='account_name',
            field=models.CharField(max_length=50, null=True, verbose_name='ユーザー名'),
        ),
    ]
