# Generated by Django 4.2 on 2024-11-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_users_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='account_id',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='ユーザーID'),
        ),
    ]
