# Generated by Django 4.2 on 2024-11-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_notification_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harassment_report',
            name='company_id',
            field=models.CharField(max_length=50, null=True, verbose_name='企業ID'),
        ),
    ]
