# Generated by Django 4.2 on 2024-11-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_harassment_report_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='superuser_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='destination',
            field=models.CharField(max_length=50, null=True, verbose_name='送り先'),
        ),
        migrations.AddField(
            model_name='notification',
            name='genre',
            field=models.BigIntegerField(null=True, verbose_name='通知種類'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_name',
            field=models.CharField(max_length=50, null=True, verbose_name='送り元'),
        ),
    ]
