# Generated by Django 4.2 on 2024-11-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_notification_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='genre',
            field=models.CharField(max_length=50, null=True, verbose_name='通知種類'),
        ),
    ]
